### ISSUE TITLE
shm_reader

### ISSUE THREAD

**Issue by tsafacjo** [pblottiere/embsys#21]
TP3
exercice 2

Juste après la  question 6 

"Placez vous maintenant dans le répertoire 2_sysprog_part2/src/shm_reader" 
De quel répertoire s'agit-il ?
il n'existe pas dans le projet

**Comment by pblottiere** [comment]
Bonjour @tsafacjo,

J'ai mis à jour le sujet du TP et rajouté le répertoire en question: https://github.com/pblottiere/embsys/tree/master/labs/sysprog/shm_reader

Bon courage et merci de m'avoir pointé le problème.
