### ISSUE TITLE
qemu.md - erreur lors du lancement du docker avec --add-cap=SYS_ADMIN

### ISSUE THREAD

**Issue by noeleel** [pblottiere/embsys#22]
J'ai eu une erreur lors du lancement du docker via la commande *docker run -it --cap-add=SYS_ADMIN pblottiere/embsys-rpi3-buildroot /bin/bash* : les droits d'accès ne m'ont pas été accordés.
Cela est probablement du au fait que j'ai du lancer mon docker en mode sudo. 

Pour régler ce problème, il est donc possible de lancer la commande *docker run -it --privileged pblottiere/embsys-rpi3-buildroot /bin/bash* qui permet de bypasser ce problème, mais donne plus d'accès sur la machine.

Il est probablement possible de régler ce problème en accordant les droits sur docker via la commande *useradd -g docker $USER* ou en modifiant directement le fichier /etc/group.

**Comment by pblottiere** [comment]
C'est corrigé (https://github.com/pblottiere/embsys/commit/5a789ba8f8f26fa5fcfe8705b25d5f7e3c7e582d).

Merci Elodie :+1:
