### ISSUE TITLE
rpi3 qemu Chroot exec format error in docker

### ISSUE THREAD

**Issue by Victorbares** [pblottiere/embsys#24]
_binfmt-support_ doit être installé sur l'hôte avec la commande 
sudo apt-get install binfmt-support

il faut aussi faire 
update-binfmts --enable qemu-arm
avant de faire le 
chroot . bin/busybox ash

**Comment by pblottiere** [comment]
C'est corrigé: https://github.com/pblottiere/embsys/commit/8a7f3f9cd76cea773393db0cd90255ef23cacbaa

Merci!
